project:
  type: website

website:
  title: "infra"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: install.qmd
        text: Installation
      - href: reference.qmd
        text: Reference

format:
  html:
    theme: cosmo
    toc: true
