# Use the official Python slim image as the base
FROM python:3.12-slim

# Avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Automatically record build time
RUN mkdir -p /usr/local/etc/container_metadata && \
    date -u '+BUILD_DATE=%Y-%m-%dT%H:%M:%SZ' \
      > /usr/local/etc/container_metadata/build_info.txt
